#!/bin/bash

ISAUR="/sbin/paru"
PARU_INST="./paru-inst"

if [ -f "$ISAUR" ]; then
    echo -e "Paru was located, moving on...\n"
else
    echo "Installing paru..."
    if [ -f "$PARU_INST" ]; then
        chmod +x "$PARU_INST"
        ./"$PARU_INST"
    else
        echo "paru-inst script not found. Please ensure it's present and try again."
        exit 1
    fi
fi

sudo sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 15\nILoveCandy/" /etc/pacman.conf

sudo pacman -S --noconfirm npm pipewire pipewire-alsa pipewire-audio pipewire-jack pipewire-media-session \
    ttf-jetbrains-mono-nerd noto-fonts-emoji noto-fonts-cjk ttf-font-awesome polkit-gnome mpv imv ffmpeg \
    hyprland dunst wofi swaybg grim slurp kitty pamixer brightnessctl waybar xdg-desktop-portal-hyprland \
    cliphist clang bluez bluez-utils pulseaudio-bluetooth gvfs-mtp btop qbittorrent thunar tumbler unzip \
    file-roller android-tools xdg-user-dirs ranger python-pillow firewalld neovim exa ripgrep perl-image-exiftool \
    duf fzf

paru -S --noconfirm mpd-mpris-bin ncmpcpp mpd nwg-displays nwg-look-bin zoxide hyprlock wlogout tldr newsboat \
    xclip urlview bat yt-dlp alacritty

echo -e "Copying config files...\n"

mkdir -p ~/tmux ~/.config

cp -r .config/themes/* /usr/share/themes/
cp -r .config/hypr/scripts/linkhandler /usr/local/bin
cp -r .config/ncmpcpp/bindings /usr/share/doc/ncmpcpp/
cp -r .config/hypr/scripts/tmuxsession /usr/local/bin/
cp -r .config/hypr/scripts/tmuxcht.sh /usr/local/bin
cp -R .config/qbittorrent ~/.config/
cp -R tmux/.tmux-cht-command ~/tmux/
cp -R .config/zathura ~/.config/
cp -R .config/btop ~/.config/
cp -R tmux/.tmux-cht-languages ~/tmux/
cp -R tmux/.tmux.conf ~/
cp -R tmux/fshow.sh ~/tmux/
cp -R tmux/fsb.sh ~/tmux/
cp -R .config/dunst ~/.config/
cp -R .config/xfce4 ~/.config/
cp -R .config/hypr ~/.config/
cp -R .config/alacritty ~/.config/
cp -R .config/mpv ~/.config/
cp -R .config/neofetch ~/.config/
cp -R .config/ranger ~/.config/
cp -R .config/waybar ~/.config/
cp -R .config/wofi ~/.config/
cp -R .config/Thunar ~/.config/
cp -R .config/nvim ~/.config/
cp -R .config/sioyek ~/.config/
cp -R .config/ncmpcpp ~/.config/
cp -R .config/mpd ~/.config/
cp -R .config/yazi ~/.config/
cp -R .config/bat ~/.config/
cp -R .config/newsboat ~/.config/
cp -R .zshrc ~/

chmod +x ~/.config/hypr/scripts/linkhandler
chmod +x ~/.config/hypr/scripts/lookup.sh
chmod +x ~/.config/hypr/scripts/tmuxsession
chmod +x ~/.config/hypr/scripts/tmuxcht.sh
chmod +x ~/tmux/fsb.sh
chmod +x ~/tmux/fshow.sh

echo -e "Script completed.\n"
echo -e "You can start Hyprland by typing Hyprland.\n"

read -n1 -rep 'Would you like to start Hyprland now? (y,n): ' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    exec Hyprland
else
    exit  
fi
