require("config.options")
require("config.keymaps")
require("config.lazy")
require("config.autocmds")
require("plugins.harpoon")
require("config.cmp")
require("plugins.oil")
require("config.snippets")
